/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type GitHubQuery = {
    repository: ({
        name: string;
    }) | null;
    viewer: {
        login: string;
        gists: {
            nodes: (({
                id: string;
            }) | null)[] | null;
        };
    };
};
export type GitHubQueryVariables = {};
