name: 'test'
on:
  push:
    branches:
      - support/*
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # use because we have to checkout our own code for local files
      - uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branches: support/v3+support/v4,support/v4+main
